;-------------------------
#include <p18f452.inc>
config	WDT = OFF
LIST	p = 18F452
;-------------------------
COUNTER 	EQU		0x000
;-------------------------
		ORG		0x00000
		MOVLW	0xF0
		MOVWF	TRISD,0
		CLRF	COUNTER,0
REPEAT
		RCALL	DELAY
		INCF	COUNTER,F,0
		MOVF	COUNTER,W
		XORLW	0x0A
		BZ		CLEAR
		MOVF	COUNTER,W
		MOVWF	LATD
		BRA		REPEAT
CLEAR
		CLRF	COUNTER
		MOVF	COUNTER,W
		MOVWF	LATD
		BRA		REPEAT
DELAY
		MOVLW	0x02	
		MOVWF	T0CON
		MOVLW	0x0B
		MOVWF	TMR0H
		MOVLW	0xDC
		MOVWF	TMR0L
		BCF		INTCON,TMR0IF		
		BSF		T0CON,TMR0ON
TEST
		BTFSS	INTCON,TMR0IF
		BRA		TEST
		BCF		INTCON,TMR0IF		
		BCF		T0CON,TMR0ON
		RETURN
		END
;----------------------------
	