		#include <p18f452.inc>		; ASM HEADER FILE
		config WDT = OFF			; WATCH DOG IS DISABLED
		LIST 	P = 18F452			; THIS INDICATE THE THE TARGET IS PIC18F452
		

		ORG		0x00000				; FIRST INSTRUCTION IS PLACED AT ADDRESS 0x00000 IN PROGRAM MEMORY
		BCF		TRISD,RD0	; RD0 OUTPU	
		BCF		LATD,RD0	; CLEAR BIT 
LOOP
		CALL	DELAY		; CALL DELAY SUBROUTINE
		BTG		LATD,RD0	; TOGGLE BIT RD7
		GOTO	LOOP		; JUMP TO LOOP(REPEAT)

DELAY
		MOVLW	0x03		; CONFIGURATION OF TIMER0 (1:16 PRESCALER) WITH 16 BIT TIMER0
		MOVWF	T0CON
		MOVLW	0x0B		; LOAD TIMER0H WITH HIGH BYTE
		MOVWF	TMR0H
		MOVLW	0xDC		; LOAD TIMER0L WITH LOW BYTE
		MOVWF	TMR0L
		BCF		INTCON,TMR0IF	; CLEAR TIMER0 FLAG BIT
		BSF		T0CON,TMR0ON	; START TIMER0 COUNTER
WAIT
		BTFSS	INTCON,TMR0IF	; IF THE TIMER0 FLAG IS RAISED SKIP THIS THE GOTO INSTRUCTION
		GOTO	WAIT
		BCF		INTCON,TMR0IF
		BCF		T0CON,TMR0ON
		RETURN					; POP TOP OF THE STACK AND RETURN BACK TO THE CALL POINT
		END
