/*
 * THIS PROGRAM IS USED TO INCREMENT A VALUE  OF VARIABLE AND DISPLAY IT IN PORTD.
 * THE VALUE IS INCREMENTED BY ONE EACH BUTTON CLICK ON RB0
 * THE VALUE IS DISPLAYED ON LEDS AFTER SENDING IT SERIALLY TO SECOND MICROCONTROLLER
 * 
 * THIS CODE DIMONSTRATE TRANSMITION OF A VALUE SERIALLY USING UART BUILT IN PIC18F
*/
#include <p18f452.h>
#pragma config WDT = OFF

unsigned char value = 0x00;
			
#pragma interrupt SERVICE			// INTERRUPT SERVICE ROUTINE
void SERVICE(void)
{
	if(INTCONbits.INT0IF)			// CHECK IF INTERRUPT OCCURS
	{	
		INTCONbits.INT0IF = 0;		// CLEAR ITS FLAG
		++value;					// INCREMENT VALUE
		if(value == 10)				// VALUE ONLY BETWEEN (0 AND 9)
			value = 0;
		PIE1bits.TXIE = 1;			// ENABLE SERIAL TRANSMITION BIT
	}
	else if(PIR1bits.TXIF)			// CHECK SERIAL COMMUNICATION TRANSMITION INTERRUPT
	{			
		TXREG = value;				// SEND VALUE SERIALLY VIA TX PIN
		PIE1bits.TXIE = 0;			// DISABLE INTERRUPT
	}
}

#pragma code VECTOR = 0x00008
void VECTOR(void)
{
	_asm
		GOTO SERVICE
	_endasm
}
#pragma code


void main(void)
{
	TRISC = 0xBF;					// TX OUTPUT/RX INPUT
	TRISB = 0xFF;					// MAKE TRISB INPIUT
	INTCONbits.INT0IE = 1;			// RB0 AS EXTERNAL INTERRUPT
	INTCONbits.INT0IF = 0;
	RCSTAbits.SPEN = 1;				// ENABLE SERIAL COMMUNICATION PORT	
	INTCONbits.GIE = 1;				// ENABLE GLOBAL INTERRUPT
	INTCONbits.PEIE = 1;			// PERIPHERAL INTERRUPT
	TXSTA = 0x20;					// CONFIGURE TRANSMITION
	SPBRG = 0x06;					// BAUD RATE
	while(1);
}
