;-------------------------
#include <p18f452.inc>
config	WDT = OFF
LIST	p = 18F452
;-------------------------
		ORG		0x00000	
		BRA		MAIN	
		ORG		0x00008			; HIGH PRIORITY LEVEL
		BRA		INTERRUPT
MAIN
		BCF		TRISD,RD0		; RD0 OUTPUT
		BSF		TRISB,RB0		; RB0 INPUT
		BSF		INTCON,GIE		; ENABLE GLOBAL INTERRUPT
		BSF		INTCON,INT0IE	; ENABLE INT0 ENABLE
		BCF		INTCON,INT0IF	; CLEAR INT0 FLAG
		BRA		$				; JUMP FOREVER
;----------------------------
INTERRUPT
		BTFSC	INTCON,INT0IF	; CHECK IF INT0 INTERRUPT OCCURS
		BRA		READ_BUTTON		; JUMP TO ISR
;----------------------------
READ_BUTTON	
		BCF		INTCON,INT0IF	; CLEAR FLAG
		BTG		LATD,RD0		; TOGGLE RD0
		RETFIE					; RETURN FROM ISR AND ENABLE GIE
;----------------------------
		END